# Generated by Django 6.0.2 on 2026-03-02 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=20, unique=True)),
                ('team_type', models.CharField(choices=[('Solo', 'Solo'), ('duo', 'Duo')], max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('year', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('residence', models.CharField(max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.team')),
            ],
        ),
    ]
